// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"
import domain "github.com/bxcodec/go-clean-arch/domain"
import mock "github.com/stretchr/testify/mock"

// ActivityUsecaseMock is an autogenerated mock type for the ActivityUsecaseMock type
type ActivityUsecaseMock struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (m *ActivityUsecaseMock) Delete(ctx context.Context, id int64) error {
	args := m.Called(ctx, id)

	return args.Error(0)
}

// Fetch provides a mock function with given fields: ctx, cursor, num
func (m *ActivityUsecaseMock) Fetch(ctx context.Context, cursor string, num int64) ([]domain.Activity, string, error) {
	args := m.Called(ctx, cursor, num)

	return args.Get(0).([]domain.Activity), args.Get(0).(string), args.Error(1)
}

// GetByID provides a mock function with given fields: ctx, id
func (m *ActivityUsecaseMock) GetByID(ctx context.Context, id int64) (domain.Activity, error) {
	args := m.Called(ctx, id)

	return args.Get(0).(domain.Activity), args.Error(1)
}

// GetByTitle provides a mock function with given fields: ctx, title
func (m *ActivityUsecaseMock) GetByTitle(ctx context.Context, title string) (domain.Activity, error) {
	args := m.Called(ctx, title)

	return args.Get(0).(domain.Activity), args.Error(1)
}

// Store provides a mock function with given fields: _a0, _a1
func (m *ActivityUsecaseMock) Store(_a0 context.Context, _a1 *domain.Activity) error {
	args := m.Called(_a0, _a1)

	return args.Error(0)
}

// Update provides a mock function with given fields: ctx, ar
func (m *ActivityUsecaseMock) Update(ctx context.Context, ar *domain.Activity) error {
	args := m.Called(ctx, ar)

	return args.Error(0)
}
