// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"
import domain "github.com/bxcodec/go-clean-arch/domain"
import mock "github.com/stretchr/testify/mock"

// TodoUsecaseMock is an autogenerated mock type for the TodoUsecaseMock type
type TodoUsecaseMock struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (m *TodoUsecaseMock) Delete(ctx context.Context, id int64) error {
	args := m.Called(ctx, id)

	return args.Error(0)
}

// Fetch provides a mock function with given fields: ctx, cursor, num
func (m *TodoUsecaseMock) Fetch(ctx context.Context, cursor string, num int64) ([]domain.Todo, string, error) {
	args := m.Called(ctx, cursor, num)

	return args.Get(0).([]domain.Todo), args.Get(0).(string), args.Error(1)
}

// GetByID provides a mock function with given fields: ctx, id
func (m *TodoUsecaseMock) GetByID(ctx context.Context, id int64) (domain.Todo, error) {
	args := m.Called(ctx, id)

	return args.Get(0).(domain.Todo), args.Error(1)
}

// GetByTitle provides a mock function with given fields: ctx, title
func (m *TodoUsecaseMock) GetByTitle(ctx context.Context, title string) (domain.Todo, error) {
	args := m.Called(ctx, title)

	return args.Get(0).(domain.Todo), args.Error(1)
}

// Store provides a mock function with given fields: _a0, _a1
func (m *TodoUsecaseMock) Store(_a0 context.Context, _a1 *domain.Todo) error {
	args := m.Called(_a0, _a1)

	return args.Error(0)
}

// Update provides a mock function with given fields: ctx, ar
func (m *TodoUsecaseMock) Update(ctx context.Context, ar *domain.Todo) error {
	args := m.Called(ctx, ar)

	return args.Error(0)
}
